=== titiyo/gameGeneratorMVC/Content/xsd/Characters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://characters.org" xmlns="http://characters.org" elementFormDefault="qualified">
  <xs:element name="personnages" type="personnagesType"/>
  <xs:complexType name="personnageType">
    <xs:sequence>
      <xs:element type="xs:string" name="nom"/>
      <xs:element type="caracteristiquesType" name="caracteristiques"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="type" use="required"/>
  </xs:complexType>
  <xs:complexType name="personnagesType">
    <xs:sequence>
      <xs:element type="personnageType" name="personnage" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="caracteristiquesType">
    <xs:sequence>
      <xs:element type="xs:int" name="vie"/>
      <xs:element type="xs:int" name="defense"/>
      <xs:element type="xs:int" name="attaque"/>
      <xs:element type="xs:int" name="initiative"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== titiyo/gameGeneratorMVC/Content/xml/Members/herbelin.benjamin/GuerreDesEtoiles/GuerreDesEtoilesCharacters.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<personnages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://Characters.org /Content/xsd/Characters.xsd">

  <personnage type="H">
    <nom>Luke</nom>
    <caracteristiques>
      <vie>100</vie>
      <defense>20</defense>
      <attaque>20</attaque>
      <initiative>20</initiative>
    </caracteristiques>
  </personnage>
  <personnage type="E">
    <nom>Zeus</nom>
    <caracteristiques>
      <vie>100</vie>
      <defense>20</defense>
      <attaque>20</attaque>
      <initiative>20</initiative>
    </caracteristiques>
  </personnage>
</personnages>

=== titiyo/gameGeneratorMVC/Content/xml/Members/julien.breton/SeigneurDesAnneaux/SeigneurDesAnneauxCharacters.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<personnages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://Characters.org /Content/xsd/Characters.xsd">
  <personnage type="H">
    <nom>Boromir</nom>
    <caracteristiques>
      <vie>200</vie>
      <defense>20</defense>
      <attaque>30</attaque>
      <initiative>10</initiative>
    </caracteristiques>
  </personnage>
  <personnage type="E">
    <nom>Gollum</nom>
    <caracteristiques>
      <vie>100</vie>
      <defense>15</defense>
      <attaque>20</attaque>
      <initiative>30</initiative>
    </caracteristiques>
  </personnage>
</personnages>
