=== titiyo/gameGeneratorMVC/Content/xsd/Game.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="jeu" type="jeuType"/>

   <xs:complexType name="jeuType">
     <xs:sequence>
        <xs:element type="xs:unsignedInt" name="id"/>
        <xs:element type="xs:date" name="datecreation"/>
        <xs:element type="xs:int" name="nbsituation"/>
        <xs:element type="xs:string" name="titre"/>
        <xs:element type="xs:string" name="createur"/>
        <xs:element type="xs:string" name="description"/>
        <xs:element type="xs:string" name="difficulte"/>
        <xs:element type="situationType" name="situation" maxOccurs="unbounded" minOccurs="0"/>
     </xs:sequence>
   </xs:complexType>

   <xs:complexType name="situationType">
       <xs:sequence>
           <xs:element type="xs:unsignedInt" name="situationCode"/>
           <xs:element type="xs:string" name="situationTitle"/>
           <xs:element type="xs:string" name="situationExposition"/>
           <xs:element type="xs:string" name="ennemi" minOccurs="0"/>
           <xs:element type="questionType" name="question"/>
       </xs:sequence>
       <xs:attribute type="xs:string" name="type" use="optional"/>
   </xs:complexType>

    <xs:complexType name="questionType">
        <xs:sequence>
            <xs:element type="xs:string" name="label"/>
            <xs:element type="choixType" name="choix"/>
            <xs:element type="suivantType" name="suivant"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="choixType">
        <xs:sequence>
            <xs:element type="repType" name="rep" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="repType">
        <xs:simpleContent>
            <xs:extension base="xs:int">
                <xs:attribute type="xs:int" name="val" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="suivantType">
        <xs:sequence>
            <xs:element type="siType" name="si"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="siType">
      <xs:sequence>
        <xs:element type="testType" name="test" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

  <xs:complexType name="testType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="xs:int" name="points"/>
      <xs:element type="xs:unsignedInt" name="code"/>
      <xs:element type="xs:int" name="pointsVictoire" minOccurs="0"/>
      <xs:element type="xs:int" name="pointsDefaite" minOccurs="0"/>
      <xs:element type="siType" name="si" minOccurs="0"/>
    </xs:choice>
    <xs:attribute type="xs:int" name="val" use="optional"/>
    <xs:attribute type="xs:int" name="vieEnnemi" use="optional"/>
    <xs:attribute type="xs:int" name="vieHeros" use="optional"/>
  </xs:complexType>
</xs:schema>

=== titiyo/gameGeneratorMVC/Content/xml/Members/julien.breton/SeigneurDesAnneaux/fileGame_julien.breton_28122013.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<jeu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://game.org /Content/xsd/game.xsd">
  <id>52be990d16681</id>
  <datecreation>28122013</datecreation>
  <nbsituation>4</nbsituation>
  <titre>SeigneurDesAnneaux</titre>
  <createur>julien.breton</createur>
  <description>GuerreDuMilieu</description>
  <difficulte>3</difficulte>
  <situation type="Narration">
    <situationCode>52be990d1736f</situationCode>
    <situationTitle>Situation Narration 1</situationTitle>
    <situationExposition>On marche en foret et arrive un croisement.</situationExposition>
    <question>
      <label>Que faire?</label>
      <choix>
        <rep val="0">Aller vers Mordor</rep>
        <rep val="1">Aller vers Fondcombe</rep>
      </choix>
      <suivant>
        <si>
          <test val="0">
            <points>30</points>
            <code>52be99c72bcde</code>
          </test>
          <test val="1">
            <points>20</points>
            <code>52be9a0688baf</code>
          </test>
        </si>
      </suivant>
    </question>
  </situation>
  <situation type="Combat">
    <situationCode>52be99c72bcde</situationCode>
    <situationTitle>Situation Combat 1</situationTitle>
    <situationExposition>Un Gollum sauvage surgit!</situationExposition>
    <ennemi>Gollum</ennemi>
    <question>
      <label>Que faire?</label>
      <choix>
        <rep val="0">Attaquer</rep>
        <rep val="1">Prendre la fuite</rep>
      </choix>
      <suivant>
        <si>
          <test val="0">
            <si>
              <test vieEnnemi="0">
                <code>52be9aa843f18</code>
                <pointsVictoire>30</pointsVictoire>
              </test>
              <test vieHeros="0">
                <code>1</code>
                <pointsDefaite>20</pointsDefaite>
              </test>
            </si>
          </test>
          <test val="1">
            <code>52be990d1736f</code>
            <points>5</points>
          </test>
        </si>
      </suivant>
    </question>
  </situation>
  <situation type="Narration">
    <situationCode>52be9a0688baf</situationCode>
    <situationTitle>Situation Narration 2</situationTitle>
    <situationExposition>Vous arrivez a Fondcombe</situationExposition>
    <question>
      <label>Que faire?</label>
      <choix>
        <rep val="0">Embrasser un elfe</rep>
        <rep val="1">Couper un arbre</rep>
      </choix>
      <suivant>
        <si>
          <test val="0">
            <points>30</points>
            <code>1</code>
          </test>
          <test val="1">
            <points>100</points>
            <code>1</code>
          </test>
        </si>
      </suivant>
    </question>
  </situation>
  <situation type="Narration">
    <situationCode>52be9aa843f18</situationCode>
    <situationTitle>Situation Narration 3</situationTitle>
    <situationExposition>Vous avez tue le Gollum ennemi, vous
    reprenez votre route.</situationExposition>
    <question>
      <label>Que faire?</label>
      <choix>
        <rep val="0">Jetter anneau dans le volcan</rep>
      </choix>
      <suivant>
        <si>
          <test val="0">
            <points>500</points>
            <code>1</code>
          </test>
        </si>
      </suivant>
    </question>
  </situation>
</jeu>

=== titiyo/gameGeneratorMVC/Content/xml/Members/herbelin.benjamin/tito/fileGame_herbelin.benjamin_30012014.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<jeu xmlns="http://game.org"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://game.org /Content/xsd/game.xsd">
  <id>52ea67c580864</id>
  <datecreation>30012014</datecreation>
  <nbsituation>2</nbsituation>
  <titre>tito</titre>
  <createur>herbelin.benjamin</createur>
  <description>il court il court</description>
  <difficulte>3</difficulte>
  <situation type="Narration">
    <situationCode>52ea67c58183c</situationCode>
    <situationTitle>A modifier</situationTitle>
    <situationExposition>A modifier</situationExposition>
    <question>
      <label>A modifier</label>
      <choix>
        <rep val="0">A modifier</rep>
        <rep val="1">reponse1</rep>
      </choix>
      <suivant>
        <si>
          <test val="0">
            <points>0</points>
            <code>52ea68472f155</code>
          </test>
          <test val="1">
            <points>10</points>
            <code>1</code>
          </test>
        </si>
      </suivant>
    </question>
  </situation>
  <situation type="Narration">
    <situationCode>52ea68472f155</situationCode>
    <situationTitle>Rue</situationTitle>
    <situationExposition>on se balade dans la
    rue</situationExposition>
    <question>
      <label>Que voulez-vous faire?</label>
      <choix>
        <rep val="0">aller rue de paris</rep>
        <rep val="1">aller rue de la paix</rep>
      </choix>
      <suivant>
        <si>
          <test val="0">
            <points>10</points>
            <code>0</code>
          </test>
          <test val="1">
            <points>20</points>
            <code>0</code>
          </test>
        </si>
      </suivant>
    </question>
  </situation>
</jeu>

=== titiyo/gameGeneratorMVC/Content/xml/Members/herbelin.benjamin/GuerreDesEtoiles/fileGame_herbelin.benjamin_30012014.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<jeu xmlns="http://game.org"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://game.org /Content/xsd/game.xsd">
  <id>52ea95808de0c</id>
  <datecreation>30012014</datecreation>
  <nbsituation>2</nbsituation>
  <titre>Monjeu</titre>
  <createur>christophe.barreto</createur>
  <description>Jeu de guerre</description>
  <difficulte>2</difficulte>
  <situation type="Narration">
    <situationCode>52ea95808e475</situationCode>
    <situationTitle>Introduction</situationTitle>
    <situationExposition>Vous etes dans une auberge.</situationExposition>
    <question>
      <label>Ou allez vous ?</label>
      <choix>
        <rep val="0">Je veux sortir d'ici et me rendre au bar</rep>
        <rep val="1">Je veux sortir d'ici et me rendre à l'armurerie</rep>
      </choix>
      <suivant>
        <si>
          <test val="0">
            <points>10</points>
            <code>1</code>
          </test>
          <test>
            <points>10</points>
            <code>52ea9a293610b</code>
          </test>
        </si>
      </suivant>
    </question>
  </situation>
  <situation type="Combat">
    <situationCode>52ea9a293610b</situationCode>
    <situationTitle>Rencontre avec Zeus</situationTitle>
    <situationExposition>Il vous defie pour tester votre valeur au combat.</situationExposition>
    <ennemi>Zeus</ennemi>
    <question>
      <label>Qu'allez vous faire ?</label>
      <choix>
        <rep val="0">Attaquer</rep>
        <rep val="1">Prendre la fuite</rep>
      </choix>
      <suivant>
        <si>
          <test val="0">
            <si>
              <test vieEnnemi="0">
                <code>0</code>
                <pointsVictoire>200</pointsVictoire>
              </test>
              <test vieHeros="0">
                <code>0</code>
                <pointsDefaite>10</pointsDefaite>
              </test>
            </si>
          </test>
          <test val="1">
            <code>0</code>
            <points>30</points>
          </test>
        </si>
      </suivant>
    </question>
  </situation>
</jeu>
